### ISSUE TITLE
Add canceled trains

### ISSUE THREAD

**Issue by pietercolpaert** [iRail/brail2gtfs-rt#15]
Canceled trains are indicated in the API as well (soon). Add it to the GTFS-RT

**Comment by brechtvdv** [comment]
Should work here: https://github.com/iRail/brail2gtfs-rt/blob/master/src/main/java/com/opentransport/rdfmapper/nmbs/ScrapeTrip.java#L235

Now set to 9999 minutes to indicate canceled stopsequence

**Comment by pietercolpaert** [comment]
Eh? 9999 is the worst thing you could have come up with imo: applications will show bogus results if not adapted

**Comment by brechtvdv** [comment]
Better option in mind? 99 for example?

**Comment by pietercolpaert** [comment]
Not at all... If the train is canceled it should be indicated as canceled?

https://developers.google.com/transit/gtfs-realtime/trip-updates

**Comment by brechtvdv** [comment]
I know for every stop of the trip if its canceled or not. When all upcoming stoptimes are canceled, I can set the ScheduleRelationship of the trip to CANCELED.
But when only certain stoptimes are partially canceled, I can set its ScheduleRelationship to SKIPPED.

Right?
