### ISSUE TITLE
What happens if the gtfs routes update

### ISSUE THREAD

**Issue by pietercolpaert** [iRail/brail2gtfs-rt#3]
Right now it's unclear to me how to update the .txt files and .json files which are now hard coded in your project repository. Wouldn't it be nicer if these files were downloaded from gtfs.irail.be or by using the code at https://github.com/iRail/brail2gtfs?

**Comment by pietercolpaert** [comment]
@TimTijssens @brechtvdv Can you guys give an update on this? Just so we know whether this is still a todo or whether there's a plan for this :)

**Comment by brechtvdv** [comment]
I think it's best to download the GTFS zip from gtfs.irail.be, extract and use that

**Comment by TimTijssens** [comment]
This is still a todo. the files are being read from the static files in the folder however it should not be so much work to implement this. I will check on this tomorrow and keep you posted.
