### ISSUE TITLE
SSL support for accessing api.irail.be

### ISSUE THREAD

**Issue by brechtvdv** [iRail/brail2gtfs-rt#31]
To trust Let's Encrypt certificate, I've added following code:

``` java
// Create a new trust manager that trust all certificates
        TrustManager[] trustAllCerts = new TrustManager[]{
            new X509TrustManager() {
                public java.security.cert.X509Certificate[] getAcceptedIssuers() {
                    return null;
                }
                public void checkClientTrusted(
                    java.security.cert.X509Certificate[] certs, String authType) {
                }
                public void checkServerTrusted(
                    java.security.cert.X509Certificate[] certs, String authType) {
                }
            }
        };

        // Activate the new trust manager
        try {
            SSLContext sc = SSLContext.getInstance("SSL");
            sc.init(null, trustAllCerts, new java.security.SecureRandom());
            HttpsURLConnection.setDefaultSSLSocketFactory(sc.getSocketFactory());
        } catch (Exception e) {
            System.out.println(e);
        }
```

And then retrieve the content:

``` java
        URL link = new URL(url);
        HttpsURLConnection connection = (HttpsURLConnection) link.openConnection();
        InputStream in = connection.getInputStream();
```

This returns following error: 

``` bash
javax.net.ssl.SSLException: java.lang.RuntimeException: Could not generate DH keypair%s
```

**Comment by pietercolpaert** [comment]
I think you can just use the https packet and it will work, no?

**Comment by pietercolpaert** [comment]
See http://alvinalexander.com/blog/post/java/simple-https-example?

**Comment by pietercolpaert** [comment]
You should be able to use the certificates installed on the system itself instead of implementing your own certificate authority in java over again...

**Comment by brechtvdv** [comment]
I'll check tonight

**Comment by brechtvdv** [comment]
I'm trying to import the certificate into the JRE by running following command in the `/usr/lib/jvm/default-java/jre/lib/security` folder:

``` bash
keytool -import -trustcacerts -keystore cacerts -storepass changeit -noprompt -alias mycert -file ~/api.irail.be.pem
```

This gives following error:

``` bash
Certificate was added to keystore
keytool error: java.io.FileNotFoundException: cacerts (Permission denied)
```

I think we'll need to ask Skyscrapers to add it as root. Not sure if this will fix it...

**Comment by pietercolpaert** [comment]
But it cannot be that difficult. Root CAs are installed and you should be
able to do https requests with some library...

Op di 11 okt. 2016 20:50 schreef Brecht Van de Vyvere <
notifications@github.com>:

**Comment by brechtvdv** [comment]
Because it's a self-signed certificate, it needs to be added to the system authority.
So this should be done on the server too.

The SSL handshake gets initiated, but it still gives the 'Could not generate DH keypair' error...
I've checked two things:
- Let's Encrypt returns a 2048 bits key, so I've set this system property:
  `System.setProperty("jdk.tls.ephemeralDHKeySize", "2048");`
- TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 is the cypher suite and should be supported on java 8 (http://docs.oracle.com/javase/8/docs/technotes/guides/security/SunProviders.html#SunJSSEProvider)

Any other ideas?

**Comment by pietercolpaert** [comment]
But it's not self-signed... It should be available as part of the normal
root CA...

Op zo 16 okt. 2016 23:15 schreef Brecht Van de Vyvere <
notifications@github.com>:

**Comment by tuukka** [comment]
Here's more information on which platforms support Let's Encrypt: https://letsencrypt.org/docs/certificate-compatibility/

SHA-2 is something that a platform codebase might not support, and "IdenTrust’s DST Root X3 certificate in its trust store" is something that might need to be added.

**Comment by brechtvdv** [comment]
Thanks @tuukka 
I see that Java >= JDK 8u101 is supported.
I was testing on 8u77..

To be continued

**Comment by brechtvdv** [comment]
The certificate is trusted so that's not the problem.

It still gives this error:
`*** Diffie-Hellman ServerKeyExchange
DH Modulus:  { ... }
DH Base:  { 2 }
Server DH Public Key:  { ... }
Anonymous
main, handling exception: java.lang.RuntimeException: Could not generate DH keypair
%% Invalidated:  [Session-1, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256]
main, SEND TLSv1.2 ALERT:  fatal, description = internal_error
main, WRITE: TLSv1.2 Alert, length = 2
main, called closeSocket()
javax.net.ssl.SSLException: java.lang.RuntimeException: Could not generate DH keypair`

**Comment by tuukka** [comment]
This test shows it's a problem with server configuration: https://www.ssllabs.com/ssltest/analyze.html?d=api.irail.be&s=176.58.110.110

Here's an nginx configuration example with Java-compatible ciphers: https://mozilla.github.io/server-side-tls/ssl-config-generator/?server=nginx-1.10.1&openssl=1.0.1e&hsts=yes&profile=intermediate

**Comment by brechtvdv** [comment]
It works! 👍

**Comment by pietercolpaert** [comment]
Thanks a lot Brecht!
