### ISSUE TITLE
Fixing url in Network Disturbances

### ISSUE THREAD

**Issue by TimTijssens** [iRail/brail2gtfs-rt#5]
Url in the network disturbances is not correct and should be fixed by adjusting the fields of the RSS

**Comment by pietercolpaert** [comment]
Can you explain this issue better? Is there a mistake in the RSS of the SNCB?

**Comment by TimTijssens** [comment]
Has been fixed so can be closed there. The parser could not read the nmbs url because it contained some parse errors.
